/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dlqtspsldjlgvysaapli"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRscXRzcHNsZGpsZ3Z5c2FhcGxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MzI0MDAsImV4cCI6MjA4NzQwODQwMH0.rr-5wRGG6gvhP8tT_Sm-PPycs8KVX_LWiZYuC89UYpU"